name: Cahyo Wicaksono - Web Developer Expert Indonesia
description: Web Developer Expert Indonesia
meta_description: "Cahyo Wicaksono - WEb Developer Expert Indonesia"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 10
baseurl: "https://cwicaksono.com/"
domain_name: "https://cwicaksono.com/"
google_analytics: "G-QPSDT14ZH5"
disqus: false
disqus_shortname: "your-disqus-shortname"

# Details for the RSS feed generator
url: "https://cwicaksono.com/"
author: "Cahyo Wicaksono"
authorTwitter: "cwicaksono"

permalink: /:year/:title/

defaults:
    - scope:
          path: "" # empty string for all files
          type: pages
      values:
          layout: default
    - scope:
          path: "" # empty string for all files
          type: posts
      values:
          layout: post
    - scope:
          path: ""
          type: drafts
      values:
          layout: post
gems: [jekyll-paginate]
paginate_path: "page:num"
